### ISSUE TITLE
请教如果集成其他厂商的SDK

### ISSUE THREAD

**Issue by Geek-James** [mdddj/shangmi_scan_data_flutter#1]
你好,请教下如果把其他厂商提供的PDA,可以红外扫码的SDK封装成flutter插件.
我的联系方式  微信:639143029
期待你的回复,非常感谢

**Comment by mdddj** [comment]
> 你好,请教下如果把其他厂商提供的PDA,可以红外扫码的SDK封装成flutter插件. 我的联系方式 微信:639143029 期待你的回复,非常感谢

具体的接入方式要看厂商的原生对接文档
